genetic_code = { 
  'ata':'i', 'atc':'i', 'att':'i', 'atg':'m', 
  'aca':'t', 'acc':'t', 'acg':'t', 'act':'t', 
  'aac':'n', 'aat':'n', 'aaa':'k', 'aag':'k', 
  'agc':'s', 'agt':'s', 'aga':'r', 'agg':'r',
  'cta':'l', 'ctc':'l', 'ctg':'l', 'ctt':'l', 
  'cca':'p', 'ccc':'p', 'ccg':'p', 'cct':'p', 
  'cac':'h', 'cat':'h', 'caa':'q', 'cag':'q', 
  'cga':'r', 'cgc':'r', 'cgg':'r', 'cgt':'r', 
  'gta':'v', 'gtc':'v', 'gtg':'v', 'gtt':'v', 
  'gca':'a', 'gcc':'a', 'gcg':'a', 'gct':'a', 
  'gac':'d', 'gat':'d', 'gaa':'e', 'gag':'e', 
  'gga':'g', 'ggc':'g', 'ggg':'g', 'ggt':'g', 
  'tca':'s', 'tcc':'s', 'tcg':'s', 'tct':'s', 
  'ttc':'f', 'ttt':'f', 'tta':'l', 'ttg':'l', 
  'tac':'y', 'tat':'y', 'taa':'*', 'tag':'*', 
  'tgc':'c', 'tgt':'c', 'tga':'*', 'tgg':'w', 
}